language: go
go_import_path: github.com/inconshreveable/log15
sudo: false

go:
  - 1.10.x
  - 1.11.x

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode10.1
cache:
  directories:
    - .cache